#!/usr/bin/env python3
"""
Scrape DOT plant codes from Tyrehood (12 pages). Keep: Factory Name, DOT, Country.

Usage:
  python build_plant_map.py --max-pages 12 --write-module --verbose
  python build_plant_map.py --reset
"""

from __future__ import annotations
import argparse, json, random, time, sys, re
from pathlib import Path
from typing import Dict, List, Tuple, Optional
import requests
from bs4 import BeautifulSoup

BASE = "https://www.tyrehood.com/en/dotdecoder.php"
ROOT = Path(__file__).resolve().parent
DATA = ROOT / "data"
DATA.mkdir(parents=True, exist_ok=True)
RAW = DATA / "raw"
RAW.mkdir(parents=True, exist_ok=True)

JSON_PATH = DATA / "plant_codes.json"
PY_PATH   = ROOT / "plant_codes.py"

UA_LIST = [
    # rotate UAs to avoid cheap blocks
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 14_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Safari/605.1.15",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36",
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
]

BASE_HEADERS = {
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
    "Accept-Language": "en-US,en;q=0.9",
    "Cache-Control": "no-cache",
    "Pragma": "no-cache",
    "Connection": "keep-alive",
}

def session() -> requests.Session:
    s = requests.Session()
    s.headers.update(BASE_HEADERS)
    s.headers["User-Agent"] = random.choice(UA_LIST)
    return s

def fetch(sess: requests.Session, page: int, retries: int = 3, backoff: float = 0.8, referer: Optional[str] = None) -> str:
    params = {"page": page}
    for i in range(retries):
        try:
            if referer:
                sess.headers["Referer"] = referer
            r = sess.get(BASE, params=params, timeout=20, allow_redirects=True)
            if r.status_code == 200 and ("Factory" in r.text or "FACTORY" in r.text or "DOT" in r.text):
                return r.text
        except Exception as e:
            if i == retries - 1:
                raise
        # rotate UA and back off
        sess.headers["User-Agent"] = random.choice(UA_LIST)
        time.sleep(backoff * (i + 1))
    # final attempt, raise for visibility
    r = sess.get(BASE, params=params, timeout=20)
    r.raise_for_status()
    return r.text

HEADER_ALIASES = {
    "FACTORY NAME": re.compile(r"^\s*factory\s*name\s*$", re.I),
    "DOT": re.compile(r"^\s*dot\s*$", re.I),
    "COUNTRY": re.compile(r"^\s*country\s*$", re.I),
}

def normalize_text(s: str) -> str:
    return re.sub(r"\s+", " ", s).strip()

def find_table_and_columns(soup: BeautifulSoup) -> Tuple[Optional[BeautifulSoup], Optional[Dict[str,int]]]:
    tables = soup.find_all("table")
    for t in tables:
        # try thead
        headers = []
        thead = t.find("thead")
        if thead:
            headers = [normalize_text(th.get_text()) for th in thead.find_all("th")]
        else:
            # fallback: first row acts as header
            first_row = t.find("tr")
            if first_row:
                headers = [normalize_text(c.get_text()) for c in first_row.find_all(["th","td"])]

        if not headers:
            continue

        # map positions
        pos: Dict[str,int] = {}
        for idx, h in enumerate(headers):
            for key, rx in HEADER_ALIASES.items():
                if rx.match(h):
                    pos.setdefault(key, idx)
        if {"FACTORY NAME","DOT","COUNTRY"} <= set(pos.keys()):
            return t, pos
    return None, None

def parse_rows(table: BeautifulSoup, col_idx: Dict[str,int]) -> List[Tuple[str,str,str]]:
    rows = table.find_all("tr")
    if not rows:
        return []

    # skip header row if headers present in the first row
    start = 0
    first = [normalize_text(c.get_text()) for c in rows[0].find_all(["th","td"])]
    if any(HEADER_ALIASES[k].match(h) for k in HEADER_ALIASES for h in first):
        start = 1

    out = []
    for r in rows[start:]:
        cells = r.find_all(["td","th"])
        if len(cells) <= max(col_idx.values()):
            continue
        factory = normalize_text(cells[col_idx["FACTORY NAME"]].get_text(" ", strip=True))
        dot     = normalize_text(cells[col_idx["DOT"]].get_text(" ", strip=True)).upper().replace(" ", "")
        country = normalize_text(cells[col_idx["COUNTRY"]].get_text(" ", strip=True))

        # Accept only 2–3 alphanumeric codes
        if not dot or not dot.isalnum() or len(dot) not in (2,3):
            continue
        out.append((dot, factory, country))
    return out

def load_db() -> Dict[str, Dict[str,str]]:
    if JSON_PATH.exists():
        return json.loads(JSON_PATH.read_text(encoding="utf-8"))
    return {}

def save_db(db: Dict[str, Dict[str,str]]):
    JSON_PATH.write_text(json.dumps(db, indent=2, ensure_ascii=False), encoding="utf-8")

def write_module(db: Dict[str, Dict[str,str]]):
    PY_PATH.write_text(
        "# Auto-generated by build_plant_map.py\n"
        "from __future__ import annotations\n"
        "from functools import lru_cache\n"
        "from typing import Dict, Optional\n\n"
        f"PLANT_MAP: Dict[str, Dict[str,str]] = {json.dumps(db, indent=2, ensure_ascii=False)}\n\n"
        "@lru_cache(maxsize=1)\n"
        "def lookup(code: str) -> Optional[Dict[str,str]]:\n"
        "    if not code:\n"
        "        return None\n"
        "    c = code.strip().upper()\n"
        "    if c in PLANT_MAP:\n"
        "        return PLANT_MAP[c]\n"
        "    # 1-char fuzzy (OCR O<->0, I<->1)\n"
        "    def norm(s):\n"
        "        return s.upper().replace('O','0').replace('I','1')\n"
        "    nc = norm(c)\n"
        "    for k,v in PLANT_MAP.items():\n"
        "        if len(k)==len(c) and sum(1 for a,b in zip(norm(k), nc) if a!=b) == 1:\n"
        "            return v\n"
        "    return None\n",
        encoding="utf-8"
    )

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--max-pages", type=int, default=12)
    ap.add_argument("--reset", action="store_true", help="delete existing JSON before scraping")
    ap.add_argument("--write-module", action="store_true", help="emit plant_codes.py")
    ap.add_argument("--verbose", action="store_true")
    ap.add_argument("--sleep", type=float, default=0.35, help="delay between page requests")
    args = ap.parse_args()

    if args.reset and JSON_PATH.exists():
        JSON_PATH.unlink()

    db = load_db()
    s = session()
    added = 0

    for page in range(1, args.max_pages + 1):
        try:
            html = fetch(s, page, referer=f"{BASE}?page={max(1,page-1)}")
        except Exception as e:
            print(f"[page {page}] fetch error: {e}", file=sys.stderr)
            continue

        # save raw for debugging when verbose
        if args.verbose:
            (RAW / f"page{page}.html").write_text(html, encoding="utf-8")

        soup = BeautifulSoup(html, "html.parser")
        table, cols = find_table_and_columns(soup)
        if not table:
            if args.verbose:
                print(f"[page {page}] no table with expected headers found")
            time.sleep(args.sleep)
            continue

        rows = parse_rows(table, cols)
        if args.verbose:
            print(f"[page {page}] parsed {len(rows)} rows")

        for dot, factory, country in rows:
            if dot not in db:
                db[dot] = {"plant": factory, "country": country, "source": "tyrehood"}
                added += 1

        time.sleep(args.sleep + random.uniform(0.05, 0.2))

    save_db(db)
    print(f"✅ Wrote {added} new plant codes to {JSON_PATH} (total: {len(db)})")
    if args.write_module:
        write_module(db)
        print(f"✅ Wrote Python module: {PY_PATH}")

if __name__ == "__main__":
    main()